name: Python Package Pytest
on: [push]

jobs:
  test-all:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.9
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        playwright install
        python -m nltk.downloader punkt stopwords
        pip install -e .[dev]
    - name: Type-checking package with mypy
      run: |
        # Manually install mypy in the standard way.
        pip --quiet install -U mypy
        # Log this mypy version for debuggability.
        mypy --version
        # Run this mypy instance against our main package.
        mypy --install-types --non-interactive .
        mypy --strict . --exclude scripts
    - name: Test with pytest
      run: |
        pytest
